/******************************************************************************/
/* DO NOT EDIT THIS FILE */
/******************************************************************************/
#include <stdio.h>
#include <string.h>
#include <stdbool.h>
#include <stdlib.h>
#include "battery_simulator.h"
#include <time.h>


#define MAXCHAR 1000


typedef enum {
    INIT = 0,
    IDLE = 1,
    DISCHARGE = 2,
    BAT_EMPTY = 3,
} t_statemachine;


/******************************************************************************/
/* DO NOT EDIT THIS FILE */
/******************************************************************************/
void measure(measured_values * data)
{
 
    static t_statemachine state = INIT;  
    static FILE *fp;
    char row[MAXCHAR];
    static bool init = false;
    static int temperature = 396;
    static float timestamp = 0.1;
    static int counter =0; 
    
    switch(state)     
    {  

       case INIT:
    	    fp = fopen ("battery_data.txt", "r");
    	    state = IDLE;
            data->timestamp = timestamp++;
           
            data->voltage = 30370+(rand() % 2);
            data->current = (rand() % 2);
            data->temperature = 234+(rand() % 2); 	  
       break;	
    
       case IDLE:
            data->timestamp = timestamp++;
           
            data->voltage = 30370+(rand() % 2);
            data->current = (rand() % 2);
            data->temperature = 234+(rand() % 2); 
    
            if (counter>=20)
            {
                state = DISCHARGE;
                counter=0;
            }
            else
            {
                counter++;
                state = IDLE; 
            }
    
            break;
    
        case DISCHARGE:
            if (feof (fp) != true)
    	    {
    	        fgets (row, MAXCHAR, fp);
    	        float timestamp_file =0;
    	        sscanf (row, "%f;%d;%d;%d", &timestamp_file, &data->voltage,
    			  &data->current, &data->temperature);
    			  data->timestamp=timestamp_file+timestamp;
    	    }
    	    else
    	    {
        	    state = BAT_EMPTY;
    	    }
            break;

        case BAT_EMPTY:
            data->timestamp = 8558.90+timestamp++;
           
            data->voltage = 24330+(rand() % 2);
            data->current = (rand() % 2);
            data->temperature = temperature-(rand() % 2) ; 
            break;           
            
            
    }
}
/******************************************************************************/
